# Data
image_size: 224
crop: False
jitter: True
noise: True

# PATH
tr_live_dataset_path: "D:/Side/CodeGate/Dataset/Train/Real"
tr_fake_dataset_path: "D:/Side/CodeGate/Dataset/Train/Fake"

val_live_dataset_path: "D:/Side/CodeGate/Dataset/Validation/Real"
val_fake_dataset_path: "D:/Side/CodeGate/Dataset/Validation/Fake"

te_live_dataset_path: "D:/Side/CodeGate/Dataset/Test/Real"
te_fake_dataset_path: "D:/Side/CodeGate/Dataset/Test/Fake"

ckp_path: "D:/Side/CodeGate/backup/DeepFake/RepVGG/try_4/ckp"
log_path: "D:/Side/CodeGate/backup/DeepFake/RepVGG/try_4/log"

# Train
cls_num: 2
seed: 1004

epoch: 30
device: "cuda"
lr: 0.0001
batch_size: 64
b1: 0.5
b2: 0.999

do_ckp_save: True
do_ckp_load: False
do_print: True
do_logging: True
